name: Run Selenium Scraper

on:
  schedule:
    - cron: '0 15 * * *' # Runs every day at 3pm UTC.
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2  # <-- CORREÇÃO AQUI: de 'actions:setup-python' para 'actions/setup-python'
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: execute python script
      run: python main.py